name: Building and then publishing Node yarn project

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Directory to run yarn audit in (default: repository root)"
        required: false
        type: string
        default: "."

      node_version:
        description: "Node version to install (e.g., 24)"
        required: false
        type: string
        default: "24"

      should_publish:
        description: "Should the project be published"
        required: false
        type: boolean
        default: false

      registry_url:
        description: "The yarn registry URL to publish to"
        required: false
        type: string
        default: ""
    
    secrets:
      node_access_token:
        description: "The yarn access token to authenticate publishing"
        required: false

jobs:
  build-publish:
    name: "Run"
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - name: Set up node and deps
        uses: UKHomeOffice/core-cloud-workflow-node-yarn-actions/actions/setup@main
        with:
          working_directory: ${{ inputs.working_directory }}
          node_version: ${{ inputs.node_version }}
          registry_url: ${{ inputs.registry_url }}

      - name: Run yarn build
        uses: UKHomeOffice/core-cloud-workflow-node-yarn-actions/actions/build@main
        with:
          working_directory: ${{ inputs.working_directory }}
      
      - name: Run yarn publish
        if: ${{ inputs.should_publish }}
        uses: UKHomeOffice/core-cloud-workflow-node-yarn-actions/actions/publish@main
        with:
          working_directory: ${{ inputs.working_directory }}
          node_access_token: ${{ secrets.node_access_token }}